project_id = "yffjnqegeiorunyvcxkn"

[functions.ai-chat]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.duel-manager]
verify_jwt = false

[functions.get-service-key]
verify_jwt = false

[functions.apply-sql]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.notification-sender]
verify_jwt = false

[functions.notification-cron]
verify_jwt = false

[functions.user-event-dispatcher]
verify_jwt = false

[functions.telegram-stars-payment]
verify_jwt = false

[functions.stars-payment-retry]
verify_jwt = false

[functions.complete-test-and-award]
verify_jwt = true

[functions.cryptomus-webhook]
verify_jwt = false

[functions.cryptomus-payment]
verify_jwt = false

[functions.tts]
verify_jwt = false
