project_id = "yffjnqegeiorunyvcxkn"

[functions.ai-chat]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.duel-manager]
verify_jwt = false

[functions.get-service-key]
verify_jwt = false

[functions.apply-sql]
verify_jwt = false
