-- Расширяем daily_bonus_def до 90 дней с разнообразными наградами
TRUNCATE TABLE daily_bonus_def;

-- Дни 1-7: Быстрая вовлеченность
INSERT INTO daily_bonus_def (day_number, reward, description) VALUES
(1, '{"xp": 10, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Первый шаг'),
(2, '{"xp": 15, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Продолжаем'),
(3, '{"xp": 20, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Набираем темп'),
(4, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost день!'),
(5, '{"xp": 30, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Почти неделя'),
(6, '{"xp": 0, "coins": 20, "boost": false, "badge": null}'::jsonb, 'День покупок'),
(7, '{"xp": 50, "coins": 10, "boost": false, "badge": "7day_streak"}'::jsonb, 'Недельный герой!'),

-- Дни 8-14
(8, '{"xp": 25, "coins": 10, "boost": false, "badge": null}'::jsonb, 'Вторая неделя'),
(9, '{"xp": 30, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Уверенный темп'),
(10, '{"xp": 35, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Десятка!'),
(11, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost заряд'),
(12, '{"xp": 40, "coins": 15, "boost": false, "badge": null}'::jsonb, 'Движение вперед'),
(13, '{"xp": 45, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Чертова дюжина'),
(14, '{"xp": 70, "coins": 20, "boost": false, "badge": "14day_streak"}'::jsonb, 'Две недели подряд!'),

-- Дни 15-21
(15, '{"xp": 35, "coins": 10, "boost": false, "badge": null}'::jsonb, 'Третья неделя'),
(16, '{"xp": 40, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Стабильность'),
(17, '{"xp": 45, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Продвижение'),
(18, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Усилитель'),
(19, '{"xp": 50, "coins": 15, "boost": false, "badge": null}'::jsonb, 'Награда дня'),
(20, '{"xp": 55, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Впечатляюще'),
(21, '{"xp": 80, "coins": 25, "boost": false, "badge": "21day_streak"}'::jsonb, 'Три недели!'),

-- Дни 22-30
(22, '{"xp": 45, "coins": 10, "boost": false, "badge": null}'::jsonb, 'Четвертая неделя'),
(23, '{"xp": 50, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Движение к цели'),
(24, '{"xp": 55, "coins": 15, "boost": false, "badge": null}'::jsonb, 'Награда'),
(25, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost мощь'),
(26, '{"xp": 60, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Ускорение'),
(27, '{"xp": 65, "coins": 20, "boost": false, "badge": null}'::jsonb, 'Приближение'),
(28, '{"xp": 70, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Месяц близко'),
(29, '{"xp": 75, "coins": 25, "boost": false, "badge": null}'::jsonb, 'Предпоследний'),
(30, '{"xp": 100, "coins": 30, "boost": true, "badge": "30day_streak"}'::jsonb, 'Месяц подряд! 🎉'),

-- Дни 31-60 (Этап закрепления)
(31, '{"xp": 50, "coins": 15, "boost": false, "badge": null}'::jsonb, 'Второй месяц'),
(32, '{"xp": 55, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Продолжаем путь'),
(33, '{"xp": 60, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Закрепление'),
(34, '{"xp": 65, "coins": 20, "boost": false, "badge": null}'::jsonb, 'Уверенность'),
(35, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Premium Boost'),
(36, '{"xp": 70, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Мастерство растет'),
(37, '{"xp": 75, "coins": 25, "boost": false, "badge": null}'::jsonb, 'Награда недели'),
(38, '{"xp": 80, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Прогресс'),
(39, '{"xp": 85, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Движение'),
(40, '{"xp": 90, "coins": 30, "boost": false, "badge": null}'::jsonb, 'Сорокадневный'),
(41, '{"xp": 60, "coins": 15, "boost": false, "badge": null}'::jsonb, 'Продолжение'),
(42, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Усилитель дня'),
(43, '{"xp": 70, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Вперед'),
(44, '{"xp": 75, "coins": 20, "boost": false, "badge": null}'::jsonb, 'Награда пути'),
(45, '{"xp": 80, "coins": 25, "boost": false, "badge": null}'::jsonb, 'Середина'),
(46, '{"xp": 85, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Прогресс'),
(47, '{"xp": 90, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Движение вперед'),
(48, '{"xp": 95, "coins": 30, "boost": false, "badge": null}'::jsonb, 'Награда'),
(49, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost заряд'),
(50, '{"xp": 100, "coins": 35, "boost": false, "badge": null}'::jsonb, 'Полтинник!'),
(51, '{"xp": 70, "coins": 20, "boost": false, "badge": null}'::jsonb, 'Дальше'),
(52, '{"xp": 75, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Стабильно'),
(53, '{"xp": 80, "coins": 25, "boost": false, "badge": null}'::jsonb, 'Награда'),
(54, '{"xp": 85, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Путь'),
(55, '{"xp": 90, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Движение'),
(56, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost мощь'),
(57, '{"xp": 95, "coins": 30, "boost": false, "badge": null}'::jsonb, 'Награда'),
(58, '{"xp": 100, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Прогресс'),
(59, '{"xp": 105, "coins": 35, "boost": false, "badge": null}'::jsonb, 'Близко к 60'),
(60, '{"xp": 120, "coins": 40, "boost": true, "badge": "60day_streak"}'::jsonb, 'Два месяца! 🔥'),

-- Дни 61-90 (Финальный этап)
(61, '{"xp": 80, "coins": 25, "boost": false, "badge": null}'::jsonb, 'Третий месяц'),
(62, '{"xp": 85, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Неостановимый'),
(63, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Мега Boost'),
(64, '{"xp": 90, "coins": 30, "boost": false, "badge": null}'::jsonb, 'Награда'),
(65, '{"xp": 95, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Путь мастера'),
(66, '{"xp": 100, "coins": 35, "boost": false, "badge": null}'::jsonb, 'Прогресс'),
(67, '{"xp": 105, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Движение'),
(68, '{"xp": 110, "coins": 40, "boost": false, "badge": null}'::jsonb, 'Награда'),
(69, '{"xp": 115, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Вперед'),
(70, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Premium Boost'),
(71, '{"xp": 120, "coins": 45, "boost": false, "badge": null}'::jsonb, 'Награда пути'),
(72, '{"xp": 90, "coins": 30, "boost": false, "badge": null}'::jsonb, 'Продолжение'),
(73, '{"xp": 95, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Стабильность'),
(74, '{"xp": 100, "coins": 35, "boost": false, "badge": null}'::jsonb, 'Награда'),
(75, '{"xp": 105, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Три четверти'),
(76, '{"xp": 110, "coins": 40, "boost": false, "badge": null}'::jsonb, 'Движение'),
(77, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Boost заряд'),
(78, '{"xp": 115, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Прогресс'),
(79, '{"xp": 120, "coins": 45, "boost": false, "badge": null}'::jsonb, 'Награда'),
(80, '{"xp": 125, "coins": 50, "boost": false, "badge": null}'::jsonb, 'Восьмидесятка!'),
(81, '{"xp": 100, "coins": 35, "boost": false, "badge": null}'::jsonb, 'Финальный рывок'),
(82, '{"xp": 105, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Близко к цели'),
(83, '{"xp": 110, "coins": 40, "boost": false, "badge": null}'::jsonb, 'Награда'),
(84, '{"xp": 0, "coins": 0, "boost": true, "badge": null}'::jsonb, 'Mega Boost'),
(85, '{"xp": 115, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Почти там'),
(86, '{"xp": 120, "coins": 45, "boost": false, "badge": null}'::jsonb, 'Предпоследняя неделя'),
(87, '{"xp": 125, "coins": 0, "boost": false, "badge": null}'::jsonb, 'Еще чуть-чуть'),
(88, '{"xp": 130, "coins": 50, "boost": false, "badge": null}'::jsonb, 'Награда'),
(89, '{"xp": 135, "coins": 55, "boost": false, "badge": null}'::jsonb, 'Последний день перед финалом'),
(90, '{"xp": 200, "coins": 100, "boost": true, "badge": "90day_iron_will"}'::jsonb, 'ЖЕЛЕЗНАЯ ВОЛЯ! 🏆');

-- Добавляем поле для восстановления streak
ALTER TABLE user_daily_bonus ADD COLUMN IF NOT EXISTS streak_restore_available BOOLEAN DEFAULT true;
ALTER TABLE user_daily_bonus ADD COLUMN IF NOT EXISTS total_restores INTEGER DEFAULT 0;