-- Revoke anon EXECUTE on 205 SECURITY DEFINER functions
-- Fixes: anon_security_definer_function_executable lint
-- All these functions require authentication; anon access is not intentional.

REVOKE EXECUTE ON FUNCTION public.activate_partner_premium(p_partner_code text, p_user_id uuid, p_utm_source text, p_utm_medium text, p_utm_campaign text, p_ip_address inet, p_user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_premium(p_user_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_premium_key(p_key text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_skin(p_user_id uuid, p_skin_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_temporary_boost(p_user_id uuid, p_boost_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_coins(p_user_id uuid, p_amount integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_partner_commission_to_hold(p_partner_id uuid, p_amount numeric, p_purchase_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_student_to_autoschool(p_partner_id uuid, p_user_id uuid, p_student_group text, p_enrollment_date date, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_to_fraud_blacklist(p_type text, p_value text, p_reason text, p_expires_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.aggregate_partner_stats_yesterday() FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_partner_promo_code(p_user_id uuid, p_promo_code text, p_base_price numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_promo_code(p_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.archive_old_conversions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.async_check_fraud_patterns(p_conversion_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_add_host_to_duel_players() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_distribute_season_rewards() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_transition_season() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_unlock_duel_pass_for_premium() FROM anon;
REVOKE EXECUTE ON FUNCTION public.buy_streak_freeze(p_user_id uuid, p_quantity integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_challenge_question(check_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_cosmetics(check_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_daily_bonus(check_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_question_report(check_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_change_password(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_partner_payout(p_payout_id uuid, p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_ad_reward_status(p_user_id uuid, p_reward_type text, p_daily_limit integer, p_cooldown_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_ai_usage_limit(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_and_auto_distribute_season_rewards() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_and_distribute_season_rewards() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_and_increment_ai_debrief_limit(user_uuid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_and_log_ended_seasons() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_cookie_stuffing(p_session_id text, p_event_type text, p_created_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_offline_action_processed(p_action_id text, p_action_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_premium_daily_bonus(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_referral_milestone() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_self_referral(p_partner_id uuid, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_test_limit(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_user_auth_method(user_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_ad_reward(p_user_id uuid, p_reward_type text, p_reward_amount integer, p_daily_limit integer, p_cooldown_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_daily_bonus_atomic(p_user_id uuid, p_server_today date, p_server_yesterday date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_daily_quest_reward(p_user_id uuid, p_user_quest_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_leaderboard_rewards(p_user_id uuid, p_season_id integer, p_position integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_premium_daily_bonus(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_technical_win(p_duel_id uuid, p_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_api_rate_log() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_boosts() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_matchmaking() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_webauthn_challenges() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_fraud_alerts() FROM anon;
REVOKE EXECUTE ON FUNCTION public.consume_webauthn_challenge(p_session_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_fraud_alert(p_partner_id uuid, p_alert_type text, p_severity text, p_description text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_or_update_session(p_user_id uuid, p_device_id uuid, p_session_token text, p_ip_address inet, p_user_agent text, p_max_sessions integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_referral(p_referrer_code text, p_referred_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_telegram_link_token() FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_transaction(p_user_id uuid, p_transaction_type text, p_amount integer, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_webauthn_challenge(p_session_id text, p_challenge text, p_challenge_type text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.daily_bonus_unified_trigger() FROM anon;
REVOKE EXECUTE ON FUNCTION public.delete_all_auth_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.delete_old_duel_data() FROM anon;
REVOKE EXECUTE ON FUNCTION public.detect_partner_fraud_patterns() FROM anon;
REVOKE EXECUTE ON FUNCTION public.duel_pass_xp(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enable_instructor_mode(p_user_id uuid, p_enabled boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.exec_sql(sql text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.finalize_race_session(p_session_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_matchmaking_opponent(p_profile_id uuid, p_bet_amount integer, p_difficulty text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_matchmaking_opponent(p_profile_id uuid, p_bet_amount integer, p_difficulty text, p_country text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_partner_link(p_partner_id uuid, p_destination text, p_utm_campaign text, p_destination_params jsonb, p_expires_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_active_exploits(p_duel_id uuid, p_my_player_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_active_reward_config(p_key text, p_season_id integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_active_season() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_ai_debrief_limit_status(user_uuid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_all_topics_progress(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_autoschool_students_progress(p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_autoschool_summary(p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_autoschool_top_students(p_partner_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_challenge_bank_questions(p_user_id uuid, p_limit integer, p_only_not_mastered boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_challenge_bank_stats(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_challenge_stats_v2(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_chat_friends(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_current_profile_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_complete(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_stats(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_super(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_super_v2(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_super_v3(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_database_size() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_duel_boost_data(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_duel_questions_raw(p_duel_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_duel_questions_secure(p_duel_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_license_points_history(p_user_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_assign_daily_quests(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_create_season_progress(p_user_id uuid, p_season_id integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_dashboard(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_funnel_by_day(p_partner_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_funnel_stats(p_partner_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_funnel_stats_optimized(p_partner_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_geo_stats(p_partner_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_link_info(p_link_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_link_stats(p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_links_stats(p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_links_with_stats(p_partner_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_payout_history(p_partner_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_partner_top_campaigns(p_partner_id uuid, p_days integer, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_passkey_for_verification(p_credential_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pdd_russia_question_by_source(p_source_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pdd_russia_ticket(p_ticket_number integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pending_fraud_alerts(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_questions_by_country(p_country text, p_limit integer, p_topic_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_duel_questions(p_count integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_duel_questions(p_limit integer, p_categories uuid[], p_difficulty text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_duel_questions(p_limit integer, p_categories uuid[], p_difficulty text, p_country text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_loot(p_loot_type text, p_pool text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_questions(country_code text, limit_count integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_random_sticker_from_pool(p_pool text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_seasonal_weekly_badge() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_sp_multiplier(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_achievements(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_badges(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_boost_inventory(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_devices(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_favorites(p_user_id uuid, p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_leaderboard_position(p_user_id uuid, p_neighbors_count integer, p_filter_type text, p_filter_value text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_loadout(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_profile_by_email(p_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_rank(p_user_id uuid, p_season_id integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_skins(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_stickers(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_transactions(p_user_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_weak_topics(p_profile_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.grant_partner_premium(p_partner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.grant_random_loot(p_user_id uuid, p_loot_data jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.grant_test_from_ad(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_duel_amount_loss() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_duel_payout_atomic() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_boost(p_user_id uuid, p_boost_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_premium_access(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_premium_forever(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_ai_usage(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_profile_stats(p_user_id uuid, p_coins integer, p_xp integer, p_sp integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_profile_value(p_profile_id uuid, p_column text, p_amount integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_profile_value_safe(p_user_identifier uuid, p_column text, p_amount integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_test_usage(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.initialize_user_achievements() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_fraudulent(p_ip inet, p_user_agent text, p_device_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_user_premium_for_limits(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.issue_premium_keys_to_partner(p_partner_id uuid, p_quantity integer, p_expires_months integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_session_to_user(p_session_id text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_telegram_to_user(_user_id uuid, _telegram_id bigint, _first_name text, _last_name text, _username text, _photo_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_telegram_user(p_token uuid, p_telegram_id bigint, p_username text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_offline_sync(p_profile_id uuid, p_action_type text, p_actions_count integer, p_success_count integer, p_failed_count integer, p_errors jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.manual_check_seasons() FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_question_started(p_duel_id uuid, p_player_id uuid, p_question_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_season_for_rewards_distribution() FROM anon;
REVOKE EXECUTE ON FUNCTION public.modify_boost_inventory(p_user_id uuid, p_boost_type text, p_change integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.on_game_session_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.on_season_end_check() FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_duel_payout(p_duel_id uuid, p_winner_id uuid, p_loser_id uuid, p_is_draw boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_ended_seasons() FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_license_event(p_user_id uuid, p_event_type text, p_custom_date timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_partner_payout(p_payout_id uuid, p_action text, p_admin_notes text, p_rejection_reason text, p_transaction_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_stars_payment_rewards(p_payment_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_test_completion(p_user_id uuid, p_test_id text, p_session_id text, p_score integer, p_questions_count integer, p_correct_count integer, p_test_duration_seconds integer, p_premium_flag boolean, p_double_sp_active boolean, p_mode text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_async_fraud_check() FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_answer(p_user_id uuid, p_question_id uuid, p_is_correct boolean, p_time_spent integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_or_update_device(p_user_id uuid, p_device_fingerprint text, p_device_name text, p_user_agent text, p_ip_address inet, p_platform text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_partner(p_name text, p_email text, p_channel_name text, p_channel_url text, p_subscribers_count integer, p_social_links jsonb, p_description text, p_partner_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_password_change(p_user_id uuid, p_ip_address inet, p_device_fingerprint text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.release_partner_commissions_from_hold() FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_partner_payout(p_partner_id uuid, p_amount numeric, p_payout_method text, p_payout_details jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.resolve_exploit(p_exploit_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.resolve_fraud_alert(p_alert_id uuid, p_resolution text, p_resolution_notes text, p_action_taken text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.revoke_partner_premium(p_partner_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rotate_daily_season_challenges() FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_user_loadout(p_user_id uuid, p_slot_1_boost_type text, p_slot_2_boost_type text, p_slot_3_boost_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.self_register_blogger(p_name text, p_platforms text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_referral_notification(p_referrer_id uuid, p_referred_name text, p_bonus_amount integer, p_notification_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.should_purchase_duel_pass(p_user_id uuid, p_season_id integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.start_premium_trial(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_achievements_with_metrics() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_achievements_with_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_all_duel_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_badge_display(p_user_id uuid, p_badge_id text, p_display boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.track_partner_conversion(p_partner_code text, p_event_type text, p_user_id uuid, p_session_id text, p_device_id text, p_fingerprint_hash text, p_utm_source text, p_utm_medium text, p_utm_campaign text, p_utm_content text, p_utm_term text, p_ip_address inet, p_user_agent text, p_country_code text, p_device_type text, p_os text, p_browser text, p_referrer_url text, p_landing_page text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_auth_event_handler() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_cleanup_challenges() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_season_rewards_processing(p_season_id integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.unlink_telegram_user(p_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_app_config(config_key text, config_value jsonb, config_description text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_app_config(key_name text, value_json jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_daily_quest_progress(p_user_id uuid, p_category text, p_delta integer, p_set_absolute boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_inactive_players() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_license_points(user_id uuid, points_delta integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_passkey_last_used(p_credential_id text, p_new_counter bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_user_achievement(p_user_id uuid, p_achievement_type text, p_progress_delta integer, p_set_absolute boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_user_loadouts_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_user_rank(p_user_id uuid, p_season_id integer, p_force_update boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_challenge_question(p_user_id uuid, p_question_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_chat_member(p_chat_id bigint, p_chat_type text, p_chat_title text, p_telegram_id bigint, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_duel_stats(p_user_id uuid, p_is_win boolean, p_is_draw boolean, p_score integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.use_boost_attack(p_duel_id uuid, p_boost_type text, p_duel_question_id uuid, p_language text, p_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.use_sticker(p_user_id uuid, p_sticker_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_promo_code(p_code text) FROM anon;

-- Total: 205 functions
