// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallback values
// Vite replaces import.meta.env.VITE_* at build time
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 
  import.meta.env.PUBLIC_SUPABASE_URL || 
  'https://yffjnqegeiorunyvcxkn.supabase.co';

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  import.meta.env.PUBLIC_SUPABASE_PUBLISHABLE_KEY || 
  import.meta.env.VITE_SUPABASE_ANON_KEY || 
  '';

// Debug: log environment variables (only in development or if explicitly enabled)
if (import.meta.env.DEV || import.meta.env.MODE === 'development') {
  console.log('🔧 Supabase Environment Variables:', {
    hasUrl: !!import.meta.env.VITE_SUPABASE_URL,
    hasKey: !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    urlLength: SUPABASE_URL.length,
    keyLength: SUPABASE_PUBLISHABLE_KEY.length,
    urlPrefix: SUPABASE_URL.substring(0, 30),
    keyPrefix: SUPABASE_PUBLISHABLE_KEY.substring(0, 20),
  });
}

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL === '' || SUPABASE_URL === 'undefined') {
  const errorMsg = '❌ VITE_SUPABASE_URL is not set! Please configure it in Vercel Environment Variables.';
  console.error(errorMsg);
  console.error('Available env vars:', Object.keys(import.meta.env).filter(k => k.includes('SUPABASE')));
  console.error('Current SUPABASE_URL value:', SUPABASE_URL);
  
  // В production показываем более понятную ошибку пользователю
  if (import.meta.env.PROD) {
    document.body.innerHTML = `
      <div style="display: flex; align-items: center; justify-content: center; min-height: 100vh; font-family: system-ui; padding: 20px; text-align: center;">
        <div>
          <h1 style="color: #ef4444; margin-bottom: 16px;">⚠️ Ошибка конфигурации</h1>
          <p style="color: #64748b; margin-bottom: 8px;">Приложение не может подключиться к базе данных.</p>
          <p style="color: #64748b; font-size: 14px;">Пожалуйста, проверьте настройки переменных окружения в Vercel.</p>
          <p style="color: #94a3b8; font-size: 12px; margin-top: 24px;">Ошибка: VITE_SUPABASE_URL не установлен</p>
        </div>
      </div>
    `;
  }
  throw new Error(errorMsg);
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === '' || SUPABASE_PUBLISHABLE_KEY === 'undefined') {
  const errorMsg = '❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set! Please configure it in Vercel Environment Variables.';
  console.error(errorMsg);
  console.error('Available env vars:', Object.keys(import.meta.env).filter(k => k.includes('SUPABASE')));
  console.error('Current SUPABASE_PUBLISHABLE_KEY length:', SUPABASE_PUBLISHABLE_KEY?.length || 0);
  
  // В production показываем более понятную ошибку пользователю
  if (import.meta.env.PROD) {
    document.body.innerHTML = `
      <div style="display: flex; align-items: center; justify-content: center; min-height: 100vh; font-family: system-ui; padding: 20px; text-align: center;">
        <div>
          <h1 style="color: #ef4444; margin-bottom: 16px;">⚠️ Ошибка конфигурации</h1>
          <p style="color: #64748b; margin-bottom: 8px;">Приложение не может подключиться к базе данных.</p>
          <p style="color: #64748b; font-size: 14px;">Пожалуйста, проверьте настройки переменных окружения в Vercel.</p>
          <p style="color: #94a3b8; font-size: 12px; margin-top: 24px;">Ошибка: VITE_SUPABASE_PUBLISHABLE_KEY не установлен</p>
        </div>
      </div>
    `;
  }
  throw new Error(errorMsg);
}

// Log configuration (without exposing the full key)
if (import.meta.env.DEV) {
  console.log('🔧 Supabase Configuration:', {
    url: SUPABASE_URL,
    keyPrefix: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...',
    keyLength: SUPABASE_PUBLISHABLE_KEY.length,
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});